# Generated by Django 4.2.7 on 2023-11-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('third_party_name', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
            ],
        ),
    ]
